change_in_place = true

# Regexes which if matched by a file path will always be excluded from
excludes = [
  "\\.gitignore",
  ".*lock",
  "\\.git/.*",
  "\\.licensure\\.yml",
  "README.*",
  "LICENSE.*",
  ".*\\.(md|rst|txt)",
  "Cargo.toml",
  ".*\\.github/.*",
]

[[license]]
files = "src/core/.*\\.rs"
ident = "MIT" 
auto_template = true 

[[license.authors]] 
name = "Core Contributor"
email = "core@example.com"

[[license]]
files = "any"
ident = "GPL-3.0"
auto_template = true

[[license.authors]] 
name = "Mathew Robinson"
email = "chasinglogic@gmail.com"
