[project]
name = "parse-comments"
version = "0.1.0"
description = "Parse the comments of helix's languages.toml"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "click-spinner>=0.1.10",
]
