[package]
name = "spdx_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
env_logger = "0.11.3"
walkdir = "2.5.0"
regex = "1.10.4"
once_cell = "1.19.0"
html_parser = "0.7.0"
html2md = "0.2.15"
thiserror = "1.0.59" 
html-escape = "0.2.13"

